version = 1

test_patterns = ["tests/**"]

exclude_patterns = [
  "packages/sandbox/**",
  "packages/sandbox_simple/**",
  "scripts/**"
]

[[analyzers]]
name = "javascript"
enabled = true

  [analyzers.meta]
  plugins = ["react"]
